# Simple profiles for about.md
simple:
  - name: Robin Van Everbroeck
    image: robinve.png.webp
    scheme: robinve.png
    comment: PhD
    style: cyanorange
  - name: Michien Ver Cruysse
    image: michielv.png.webp
    scheme: michielv.png
    comment: PhD
    style: purplecyan
  - name: Maxim Van Assel
    scheme: maximva.png
    comment: PhD
    style: purpleorange
  - name: Wouter Saelens
    image: wouters.jpg
    scheme: wouters.png
    style: purplecyanorange
  - name: Yujin Kim
    scheme: yujink.png
    comment: Graduate Student
    style: purplecyan
  - name: Manas Raiker
    scheme: manasr.png
    comment: PhD - Joining 2026
    style: purpleorange
  - name: Amir Ebrahimi
    scheme: amire.png
    comment: PhD - Joining 2026
    style: purplecyan

# Full profiles for profiles.md (team page)
full:
  - align: right
    content: about/robinve.md
    scheme: robinve.png
    image_circular: false
  - align: right
    content: about/michielv.md
    scheme: michielv.png
    image_circular: false
  - align: right
    content: about/maximva.md
    scheme: maximva.png
    image_circular: false
  - align: right
    content: about/wouters.md
    scheme: wouters.png
    image_circular: false