# Simple profiles for about.md
simple:
  - name: Robin Van Everbroeck
    image: robinve.png.webp
    scheme: robinve.png
    comment: PhD
    style: cyanorange
    content: about/robinve.md
  - name: Michiel Ver Cruysse
    image: michielv.png.webp
    scheme: michielv.png
    comment: PhD
    style: purplecyan
    content: about/michielv.md
  - name: Maxim Van Assel
    scheme: maximva.png
    comment: PhD
    style: purpleorange
    content: about/maximva.md
  - name: Wouter Saelens
    image: wouters.jpg
    scheme: wouters.png
    style: purplecyanorange
    content: about/wouters.md
  - name: Yujin Kim
    scheme: yujink.png
    comment: Graduate Student
    style: purplecyan
  - name: Manas Raiker
    scheme: manasr.png
    comment: PhD - Joining 2026
    style: purpleorange
  - name: Amir Ebrahimi
    scheme: amire.png
    comment: PhD - Joining 2026
    style: purplecyan